#!/usr/bin/env python
#encoding=utf8


def encode(message, rails):
    message = "".join(ch for ch in message if ch.isalnum())
    fence = [[""] * len(message)] * rails
    for i, ch in enumerate(message):
        order = i % (2 * rails - 2)
        fence[i][i]


def decode(encoded_message, rails):
    fence = [[""] * len(encoded_message)] * rails
    print(fence)


encode("WE ARE DISCOVERED FLEE AT ONCE", 3)


0 1 2 3 4 5 6 7 8 9

rails = 4

0 1 2 3 
