#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail


# define tasks here
get_current_job (){
  ls -lhtr python | tail -n 1 | awk '{print $NF}'
}

test (){
  current=$(get_current_job)
  file_prefix=`echo $current | sed "s/-/_/g"`
  python python/$current/${file_prefix}_test.py
  python3 python/$current/${file_prefix}_test.py
}

submit () {
  current=$(get_current_job)
  file_prefix=`echo $current | sed "s/-/_/g"`
  exercism submit python/$current/${file_prefix}.py
  git add "python/$(get_current_job)"
  git commit -vs
  exercism fetch
  current=$(get_current_job)
  file_prefix=`echo $current | sed "s/-/_/g"`
  echo -e "#!/usr/bin/env python\n#encoding=utf8\n\n" > /tmp/exercism.tmp
  cat python/$current/${file_prefix}.py >> /tmp/exercism.tmp
  mv /tmp/exercism.tmp python/$current/${file_prefix}.py
}

_less () {
  current=$(get_current_job)
  less python/$current/README.md
}

clean (){
  echo "do clean here"
}

# main start here
command=${1:-""}

if [ -n "$(type -t $command)" ] && [ "$(type -t $command)" = function ]
then
  eval $command
  exit $?
fi

case "$command" in
  l)
    _less
  ;;
  s)
    submit
  ;;
  t)
    test
  ;;
  *)
    clean
esac
